// Generated by scripts/recovery/generate-shims.mjs — a compat shim: no logic, only the owner's exports under the old names.
import { createDatePicker, renderWith } from "obix-core-component";
export { createDatePicker } from "obix-core-component";
export type { DatePickerConfig, DatePickerState } from "obix-core-component";
export const renderDatePicker = renderWith(createDatePicker);
